### PR TITLE
Add option to sort by song author

### PR DESCRIPTION
**Pull request by lhvy**

### CODE REVIEW

**Comment by kinsi55** [comment]
This has been suggested before, however I am opposed to this. In my opinion this doesnt really have any use. If you are looking to play maps from a specific mapper you can just search for that mapper, and beyond that I dont really see any reason one would possibly want to sort by the mapper. If you know one feel free to let me know

**Comment by lhvy** [comment]
By the way, I don't really use Visual Studio much, so this might be something I could fix on my end, but maybe you could add `.vs/*` to the .gitignore to stop auto generated files from being committed accidentally?

**Comment by lhvy** [comment]
> 
> 
> This has been suggested before, however I am opposed to this. In my opinion this doesnt really have any use. If you are looking to play maps from a specific mapper you can just search for that mapper, and beyond that I dont really see any reason one would possibly want to sort by the mapper. If you know one feel free to let me know

This PR adds sorting by the author of the song, not the mapper? Apologies if that was unclear in any way.

**Comment by kinsi55** [comment]
Thats my bad, I read too quickly and brained too little - However, thats a similar case in my opinion. I personally dont really see any use in sorting by the song interpret

**Comment by lhvy** [comment]
I guess I thought it would just be added convenience for anyone who wants it, and it stuck me as odd that there was already a sort by mapper feature but not a sort by song author feature. Obviously it is up to you which functionality you want in the plugin, I just noticed this wouldn't be too hard to add so decided to give it a shot.

**Comment by kinsi55** [comment]
Hm, you are right, there in fact is a sort by mapper option - I am not entirely sure why that is there, I might possibly even end up even removing that as I try to keep the UI as uncluttered as possible by including only those things that are enough for 99% of the people. I dont think I ever saw anyone actually use that sort.

I plan to make sorts and filters extensible so that anyone can add any custom ones of their own without needing to modify BetterSongList directly. Once that is the case I might create sort / filter addons for things like sorting by the Song author for those that are interested in such a thing, but as it is I'll be declining this for now sorry.

**Comment by kinsi55** [comment]
> By the way, I don't really use Visual Studio much, so this might be something I could fix on my end, but maybe you could add `.vs/*` to the .gitignore to stop auto generated files from being committed accidentally?

Also I'm not too sure what you mean by that, are you using VS Code? I dont have any .vs directory

**Comment by kinsi55** [comment]
Hm weird, I'm using the same. I'll add that to my gitignore moving forward, thank you.

**Pull request closed without merging**
